// Table schemas for the Query Agent
export interface TableSchema {
  name: string;
  schema: string;
}

export const TABLE_SCHEMAS: Record<string, string> = {
  orders: `
CREATE TABLE orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL CHECK (platform IN ('toast', 'square', 'clover')),
  platform_order_id text NOT NULL,
  external_id text,
  status text,
  state text,
  payment_status text,
  created_date timestamptz,
  modified_date timestamptz,
  opened_date timestamptz,
  closed_date timestamptz,
  paid_date timestamptz,
  promised_date timestamptz,
  estimated_fulfillment_date timestamptz,
  delivered_date timestamptz,
  dispatched_date timestamptz,
  currency text DEFAULT 'USD',
  subtotal_amount numeric(10,2),
  tax_amount numeric(10,2),
  tip_amount numeric(10,2),
  discount_amount numeric(10,2),
  service_charge_amount numeric(10,2),
  total_amount numeric(10,2) NOT NULL,
  customer_id uuid REFERENCES customers(id),
  customer_first_name text,
  customer_last_name text,
  customer_email text,
  customer_phone text,
  order_type text,
  dining_option text,
  source text,
  number_of_guests integer,
  display_number text,
  tab_name text,
  location_id uuid REFERENCES locations(id),
  table_id text,
  service_area_id text,
  revenue_center_id text,
  channel_id text,
  delivery_address jsonb,
  delivery_notes text,
  delivery_state text,
  line_items jsonb,
  payments jsonb,
  discounts jsonb,
  taxes jsonb,
  service_charges jsonb,
  platform_data jsonb,
  is_voided boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  is_test_mode boolean DEFAULT false,
  is_tax_exempt boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(platform, platform_order_id)
);`,

  customers: `
CREATE TABLE customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL CHECK (platform IN ('toast', 'square', 'clover')),
  platform_customer_id text NOT NULL,
  external_id text,
  reference_id text,
  given_name text,
  family_name text,
  first_name text,
  last_name text,
  company_name text,
  business_name text,
  nickname text,
  email_address text,
  phone_number text,
  note text,
  creation_source text,
  customer_since timestamptz,
  marketing_allowed boolean DEFAULT false,
  email_unsubscribed boolean DEFAULT false,
  birth_year integer,
  birth_month integer,
  birth_day integer,
  address_line_1 text,
  address_line_2 text,
  address_line_3 text,
  locality text,
  city text,
  administrative_district_level_1 text,
  state text,
  postal_code text,
  zip text,
  country text,
  location_id uuid REFERENCES locations(id),
  addresses jsonb,
  email_addresses jsonb,
  phone_numbers jsonb,
  cards jsonb,
  group_ids jsonb,
  segment_ids jsonb,
  orders jsonb,
  preferences jsonb,
  metadata jsonb,
  platform_data jsonb,
  version bigint,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(platform, platform_customer_id)
);`,

  users: `
CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL CHECK (platform IN ('toast', 'square', 'clover', '7shifts')),
  platform_user_id text NOT NULL,
  external_id text,
  reference_id text,
  employee_id text,
  custom_id text,
  first_name text,
  last_name text,
  chosen_name text,
  preferred_first_name text,
  preferred_last_name text,
  nickname text,
  pronouns text,
  email text,
  phone_number text,
  phone_country_code text,
  mobile_number text,
  home_number text,
  address text,
  city text,
  state_province text,
  postal_code text,
  status text,
  role text,
  user_type text,
  is_owner boolean DEFAULT false,
  is_active boolean DEFAULT true,
  invite_status text,
  hourly_wage numeric(10,2),
  wage_type text,
  max_weekly_hours text,
  skill_level integer,
  birth_date date,
  timezone text,
  language text DEFAULT 'en',
  photo text,
  notes text,
  pin text,
  passcode text,
  created_date timestamptz,
  modified_date timestamptz,
  deleted_date timestamptz,
  claimed_time timestamptz,
  invited_date timestamptz,
  invite_accepted_date timestamptz,
  location_id uuid REFERENCES locations(id),
  job_assignments jsonb,
  assigned_locations jsonb,
  roles jsonb,
  wage_overrides jsonb,
  permissions jsonb,
  platform_data jsonb,
  is_deleted boolean DEFAULT false,
  invite_sent boolean DEFAULT false,
  is_new boolean DEFAULT true,
  appear_as_employee boolean DEFAULT true,
  subscribe_to_updates boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  sms_schedules boolean DEFAULT false,
  notify_overtime_risk boolean DEFAULT false,
  is_overtime_exempt boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(platform, platform_user_id)
);`,

  products: `
CREATE TABLE products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL CHECK (platform IN ('toast', 'square', 'clover')),
  platform_product_id text NOT NULL,
  external_id text,
  name text NOT NULL,
  description text,
  kitchen_name text,
  alternate_name text,
  price numeric(10,2),
  cost numeric(10,2),
  price_type text,
  pricing_strategy text,
  price_without_vat numeric(10,2),
  sku text,
  plu text,
  code text,
  upc text,
  category_id text,
  category_name text,
  item_group_id text,
  is_available boolean DEFAULT true,
  is_hidden boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  is_revenue boolean DEFAULT true,
  is_discountable boolean DEFAULT true,
  stock_count integer,
  auto_manage_stock boolean DEFAULT false,
  unit_name text,
  unit_of_measure text,
  calories integer,
  weight numeric(10,2),
  weight_unit_of_measure text,
  length numeric(10,2),
  width numeric(10,2),
  height numeric(10,2),
  dimension_unit_of_measure text,
  image_url text,
  color_code text,
  pos_name text,
  pos_button_color_light text,
  pos_button_color_dark text,
  sort_order integer,
  default_tax_rates boolean DEFAULT true,
  tax_inclusion text,
  prep_time integer,
  prep_stations jsonb,
  variations jsonb,
  modifiers jsonb,
  modifier_groups jsonb,
  options jsonb,
  categories jsonb,
  tags jsonb,
  tax_rates jsonb,
  images jsonb,
  allergens jsonb,
  content_advisories jsonb,
  platform_data jsonb,
  location_id uuid REFERENCES locations(id),
  created_date timestamptz,
  modified_date timestamptz,
  deleted_date timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(platform, platform_product_id)
);`,

  shifts: `
CREATE TABLE shifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL CHECK (platform IN ('toast', 'square', 'clover', '7shifts')),
  platform_shift_id text NOT NULL,
  external_id text,
  user_id uuid REFERENCES users(id),
  platform_user_id text,
  location_id uuid REFERENCES locations(id),
  department_id text,
  role_id text,
  job_id text,
  start_time timestamptz,
  end_time timestamptz,
  actual_start_time timestamptz,
  actual_end_time timestamptz,
  override_start_time timestamptz,
  override_end_time timestamptz,
  override_start_user_id uuid REFERENCES users(id),
  override_end_user_id uuid REFERENCES users(id),
  status text,
  attendance_status text,
  publish_status text,
  is_open boolean DEFAULT false,
  is_published boolean DEFAULT false,
  is_draft boolean DEFAULT true,
  is_template boolean DEFAULT false,
  notes text,
  breaks jsonb,
  platform_data jsonb,
  created_date timestamptz,
  modified_date timestamptz,
  deleted_date timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(platform, platform_shift_id)
);`,

  tasks: `
CREATE TABLE tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL CHECK (platform IN ('7shifts', 'toast', 'square', 'clover')),
  platform_task_id text NOT NULL,
  task_template_uuid text,
  task_list_id text,
  task_list_title text,
  task_list_template_uuid text,
  title text NOT NULL,
  description text,
  status text,
  priority text,
  assigned_to uuid REFERENCES users(id),
  platform_user_id text,
  location_id uuid REFERENCES locations(id),
  department_id text,
  role_id text,
  company_id text,
  start_time timestamptz,
  due_time timestamptz,
  completed_at timestamptz,
  completion_type text,
  completion_value text,
  completion_unit text,
  recurrence_interval text,
  recurrence_rule text,
  tags jsonb,
  assignments jsonb,
  platform_data jsonb,
  created_date timestamptz,
  modified_date timestamptz,
  deleted_date timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(platform, platform_task_id)
);`,

  inventory: `
CREATE TABLE inventory (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL CHECK (platform IN ('toast', 'square', 'clover')),
  platform_inventory_id text NOT NULL,
  product_id uuid REFERENCES products(id),
  platform_product_id text,
  location_id uuid REFERENCES locations(id),
  name text,
  alternate_name text,
  sku text,
  code text,
  stock_count integer,
  quantity numeric(10,2),
  reorder_threshold integer,
  reorder_quantity integer,
  unit_name text,
  unit_type text,
  is_available boolean DEFAULT true,
  is_hidden boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  auto_manage boolean DEFAULT false,
  cost numeric(10,2),
  price numeric(10,2),
  price_without_vat numeric(10,2),
  price_type text,
  storage_location text,
  item_group_id text,
  category_id text,
  options jsonb,
  tax_rates jsonb,
  tags jsonb,
  categories jsonb,
  modifiers jsonb,
  modifier_groups jsonb,
  platform_data jsonb,
  created_date timestamptz,
  modified_date timestamptz,
  deleted_date timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(platform, platform_inventory_id)
);`,

  locations: `
CREATE TABLE locations (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  address text,
  city text,
  state text,
  postal_code text,
  country text,
  phone text,
  email text,
  timezone text,
  currency text DEFAULT 'USD',
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);`,

  integrations: `
CREATE TABLE integrations (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  location_id uuid NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  integration_type varchar(50) NOT NULL CHECK (integration_type IN ('posSystem', 'taskTraining', 'scheduling', 'financialManagement')),
  provider_type varchar(50) NOT NULL,
  api_key_hash text NOT NULL,
  connection_status varchar(20) DEFAULT 'Checking...' CHECK (connection_status IN ('Checking...', 'Connected', 'Disconnected')),
  settings jsonb,
  last_sync_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(location_id, integration_type)
);`
};

export function getSchemaForTables(tableNames: string[]): Record<string, string> {
  const schemas: Record<string, string> = {};
  tableNames.forEach(tableName => {
    // Try exact match first
    if (TABLE_SCHEMAS[tableName]) {
      schemas[tableName] = TABLE_SCHEMAS[tableName];
    } else {
      // Try case-insensitive match and title-to-name mapping
      const lowerTableName = tableName.toLowerCase();
      
      // Map common title variations to actual table names
      const titleToNameMap: Record<string, string> = {
        'orders': 'orders',
        'customers': 'customers', 
        'users': 'users',
        'users/employees': 'users',
        'products': 'products',
        'products/menu items': 'products',
        'shifts': 'shifts',
        'employee shifts': 'shifts',
        'tasks': 'tasks',
        'tasks & training': 'tasks',
        'inventory': 'inventory',
        'locations': 'locations',
        'restaurant locations': 'locations',
        'integrations': 'integrations',
        'system integrations': 'integrations'
      };
      
      const actualTableName = titleToNameMap[lowerTableName];
      if (actualTableName && TABLE_SCHEMAS[actualTableName]) {
        schemas[actualTableName] = TABLE_SCHEMAS[actualTableName];
      }
    }
  });
  return schemas;
}
